config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :chat_rooms

  mount ActionCable.server => '/cable'

  root 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/callback.rb
class Callback < ApplicationRecord
end

app/models/categoriesproject.rb
class Categoriesproject < ApplicationRecord
  has_many :chatrooms
  has_many :languages
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  belongs_to :categoriesproject
  has_many :messages, dependent: :destroy
  validates_presence_of :github_url
  validates_presence_of :description
end

app/models/language.rb
class Language < ApplicationRecord
  belongs_to :categoriesproject
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]


  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
# applications controller authroizes user
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
# chat rooms controller is the single controller that deals with messages
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if params[:chat_room][:github_url].include?('https://github.com/')
      @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

# TODO: I want users to be able to sort their project into a language category.
# Or multiple languages. I want users to be able to search through those languages
# and find projects with the languages that they want to work in.

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

  def edit
    @chat_room = ChatRoom.find(params[:id])
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title, :description, :github_url)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
# callbacks controller
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.where(email: request.env['omniauth.auth'].info.email).first
    unless @user
      @user = User.new(
        email: request.env['omniauth.auth'].info.email,
        password: Devise.friendly_token[0, 20],
        token: request.env['omniauth.auth'].credentials.token,
        uid: request.env['omniauth.auth'].uid
      )
      @user.save
    else
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', :kind => 'Google'
    end
    sign_in @user
    redirect_to chat_rooms_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, opts = {})
    opts[:alt] = user.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
              opts
  end
end

app/views/chat_rooms/edit.html.erb
<div class="wholePage">

<div class="lightercolor">
<p><%= @chat_room.title %></p>
</div>

<div class="lightercolor">
<p><%= @chat_room.description %></p>
</div>

<a href="<%= @chat_room.github_url %>">Github</a>
<p><%= link_to "Enter #{@chat_room.title}", chat_room_path(@chat_room) %></p>
</div>

app/views/chat_rooms/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="allProjects">
    <h1>PROJECTS</h1>
    <p class="button"><%= link_to 'New Collaboration', new_chat_room_path, class: 'btn btn-primary' %></p>

    <% @chat_rooms.each do |chat_room| %>
    <ul class="chatInfo">
      <div class="chatName">
        <%= link_to "#{chat_room.title}", edit_chat_room_path(chat_room) %>
      </div>
      <% if chat_room.messages.all.last %>
        <p class="workUpdated">Last updated at <%= chat_room.messages.all.last.created_at.strftime("%F") %></p>
      <% else %>
        <p>Be the first to contribute to this!</p>
        <% end %>
    </ul>
    <% end %>

    </div>
  </body>
</html>

app/views/chat_rooms/new.html.erb
<div class="createAProject">

<div class="formCreate">
<h1 class="colorDarkBrown">CREATE A PROJECT</h1>
<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.label :github %>
    <%= f.text_field :github_url, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>
</div>

</div>

app/views/chat_rooms/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <h1><%= @chat_room.title %></h1>

  <div id="messages" data-chat-room-id="<%= @chat_room.id %>">
    <%= render @chat_room.messages %>
  </div>

  <hr>
  <%= form_for @message, url: '#' do |f| %>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>

  <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
  <% end %>
    <script src="https://plus.google.com/js/client:plusone.js"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script src="https://apis.google.com/js/client:platform.js" async defer></script>
    <div id="placeholder-rr"></div>
    <script>
      gapi.hangout.render('placeholder-rr', {
       'render': 'createhangout',
       'initial_apps': [{'app_id' : '184219133185', 'start_data' : 'dQw4w9WgXcQ', 'app_type' : 'ROOM_APP' }],
       'widget_size': 175
     });
    </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Screen Share</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Asap" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-dark bg-inverse">
  <%= link_to 'Screen Share', root_path, class: 'navbar-brand' %>

  <% if user_signed_in? %>
    <ul class="nav navbar-nav pull-xs-right">
      <li class="nav-item">
        <span class="text-muted">Logged in as <strong><%= current_user.name %></strong></span>
      </li>
      <li class="nav-item active">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  <% end %>
</nav>

<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
        <%= gravatar_for message.user %>
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>

  </div>
</div>